### ISSUE TITLE
Getting started / first steps

### ISSUE THREAD

**Issue by cure53** [mozilla/sanitizer-polyfill#1]
Hey all, thanks for setting this up, very happy to help with implementing and maintaining this.

First questions first, is there any "standard" we should obey to regarding how write this polyfill?
Do we agree that for example this is a a good guide we can work with or is there any better material?

https://dev.to/reachtokish/write-your-own-polyfill-kbl

Further, should we also maintain a test suite that for example tests if the merging of config values in this polyfill is doing the same as the browser would do etc.?

**Comment by mozfreddyb** [comment]
I honestly don't know if there's a standard but it looks like one can draw inspiration from other repos.

The linked guide seems low in depth, but also non-controversial. I can agree with that.

For tests, we have some in https://github.com/web-platform-tests/wpt/tree/master/sanitizer-api that are already integrated into Chrome's & Firefox's CI. The test suite of this polyfill ought to run those. TT seems to be doing something similar in e.g., https://github.com/w3c/webappsec-trusted-types/blob/main/karma.conf.js

**Comment by mozfreddyb** [comment]
I've written the polyfill-logic in polyfill.js, just to make the interface with the document "right".
The sanitize-functions are no-ops, but can be implemented mostly aside of the polyfilling things. I will file issues and annotate the code with the issue numbers to get things going. I think we can close this one.
