### ISSUE TITLE
Polyfill removes URLs with custom protocol

### ISSUE THREAD

**Issue by WIStudent** [mozilla/sanitizer-polyfill#121]
I tried the polyfill and noticed that it removes URLs with custom protocol from `<a>` tags. Inserting
```html
<a href="myprotocol://abc">click me</a>
```
on the demo page results in 
```
<div><a>click me</a></div>
```

If I enable the native Sanitizer API implementation in Firefox the demo page then returns
```html
<div><a href="myprotocol://abc">click me</a></div>
```

This lets me believe that URLs with custom protcols should not be removed. If I understood the spec correctly only URLs starting with `javascript:` need to be removed.

I saw that DOMPurify has the options `ALLOW_UNKNOWN_PROTOCOLS` and `ALLOWED_URI_REGEXP`, although I am not sure how they need to be used to keep URLs with custom protocols but remove all other malicious URLs. (Are URLs starting with `javascript:` really all that need to be removed or are there others that also need to be taken into consideration?)

**Comment by mozfreddyb** [comment]
Hi! Thanks for filing the issue. I believe there's a bigger spec question about URLs that we probably need to answer eventually. For now, I suppose it would be good to align with the spec and only remove `javascript`.

Btw, are you interested in prototyping a patch? :)
