### ISSUE TITLE
Polyfill has second parameter of setHTML incorrect

### ISSUE THREAD

**Issue by Sora2455** [mozilla/sanitizer-polyfill#140]
The polyfill assumes that the second parameter to setHTML is a sanitiser object, when it's actually a dictionary with a sanitiser member: https://developer.mozilla.org/en-US/docs/Web/API/Element/setHTML

**Comment by mozfreddyb** [comment]
Ah, that's indeed wrong. Thanks! Are you interested in writing a pull request? :)

**Comment by Sora2455** [comment]
@mozfreddyb Pull request up.
