### ISSUE TITLE
Polyfill demo is broken

### ISSUE THREAD

**Issue by mikkorantalainen** [mozilla/sanitizer-polyfill#159]
The demo tries to include file https://mozilla.github.io/sanitizer-polyfill/dist/sanitizer-polyfill.js which doesn't exist.

The demo is available in address https://mozilla.github.io/sanitizer-polyfill/demo/

**Comment by mozfreddyb** [comment]
I think it works again... it seems we had a glitch with github action workflows racing with each other. Can you please confirm?

**Comment by mozfreddyb** [comment]
works for me.
