### ISSUE TITLE
setup prettier to run automatically

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/sanitizer-polyfill#20]
.

**Comment by Bl4ck-h00d** [comment]
Hi!
I would like to work on this. Can you help me how to get started?

**Comment by mozfreddyb** [comment]
Prettier (https://prettier.io/) is already declared as a dev-dependency.
The desired outcome for this issue is to make sure that it's run as part of the "lint" script in package.json and complain if stuff is not properly formatted.

I'm sure the npm package.json & prettier docs will suffice.

**Comment by Bl4ck-h00d** [comment]
Hey, I found a package [prettier-eslint](https://www.npmjs.com/package/prettier-eslint). This formats code via prettier and then passes the result of that to `eslint --fix`. So, should I use it?
