### ISSUE TITLE
Improve demo/index.html to test the sanitizer with some pre-defined mock-elements

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/sanitizer-polyfill#21]
The goal is to make the demo at https://mozilla.github.io/sanitizer-polyfill/demo/ more useful.

There's a test-bed for the old Sanitizer API at https://freddyb.neocities.org/sanitizer.html, which is providing the _outdated_ API.  This is my code, so it can be liberally copied & modified without any extra permission.

Please remove the `sanitize` invocations with a `sanitizeFor()` invocation. Not sure if the "for" parameter should be hard-coded or customizable. The "Example input" will be useful to keep. Please also keep the link to `?#mustpolyfill` in the top, as it will help enforce testing the polyfill, even when the user's browser is already providing a `Sanitizer` object.

**Comment by Bl4ck-h00d** [comment]
Hi! Can you please explain to me how this project works and how can I test it locally? Also, how should I approach this issue?

**Comment by mozfreddyb** [comment]
This whole project is a JavaScript implementation of an upcoming web standard - [the sanitizer api](https://wicg.github.io/sanitizer-api/). Those JS-implementations of a not-yet-implemented standard are called "polyfill".

The demo page linked above is running the polyfill in an empty page. In itself, that's not very useful. By loading the page, you have a `Sanitizer` object and the `.setHTML` function on html element objects.

Now, the demo page should be extended to make use of the Sanitizer API.
The sanitizer.html (2nd link in my comment on top) is doing exactly, but for an earlier version of the Sanitizer API, one which exposed different functionality. The idea is to redo the sanitizer.html-demo for the new methods (e.g., setHTML).

Makes sense?

**Comment by Bl4ck-h00d** [comment]
[
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/61791315/128130725-743be0f2-bb9e-4a8f-9a38-b2537a337652.gif)
](url)

**Is this ok?**

**Comment by mozfreddyb** [comment]
I think this is a good step. Btw, what does the Sanitize call exactly?
You can reuse most of the CSS style, code & logic from https://freddyb.neocities.org/sanitizer.html (execpt the sanitize calls obviously).

**Comment by Bl4ck-h00d** [comment]
Sanitize calls setHTML(input, {}) function.

**Comment by mozfreddyb** [comment]
OK, please use the layout from the sanitizer.html on neocities (textara for input, button, textarea for output source-text (please use `outerHTML`), area for output rendered)

Given this, I suggest we change the button-stuff to
1) fill input with an example 
2) select a context element (<div>, <table>, >select>
3) button that say `context.setHTML()` and creates the context element on the-fly to be appended to the preview


Makes sense?

**Comment by Bl4ck-h00d** [comment]
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/61791315/128146455-101dc721-77cd-4daf-96b2-e81a3636de09.gif)
I am working on selecting the context part, but other than that rest is good?

**Comment by mozfreddyb** [comment]
yup, go for it! Let's iterate on code rather than screenshots. Can you open a pull request? :)

**Comment by Bl4ck-h00d** [comment]
#25

**Comment by mozfreddyb** [comment]
@Bl4ck-h00d awesome job in #25! do you want to follow-up with some work around the buttons and defaults?

**Comment by Bl4ck-h00d** [comment]
Sure, would love to! :)

**Comment by mozfreddyb** [comment]
looking forward to your next pull request then!

**Comment by mozfreddyb** [comment]
This isn't done, but I'm filing a follow-up issue.
