### ISSUE TITLE
Fix compat eslint issue 

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/sanitizer-polyfill#219]
The code in demo/script.js is causing an issue with the `compat` eslint rule, stating that `Sanitizer` is not available in Safari. 
That's a known and acceptable compat issue.

To fix this issue, we should just add a line `// eslint-disable-next-line compat/compat` (is this the right syntax).

Outside contributions are welcome!

https://github.com/mozilla/sanitizer-polyfill/actions/runs/4665993201/jobs/8260052551?pr=215 has more information.

**Comment by mozfreddyb** [comment]
@sumitshinde-84  Please go ahead and open a Pull Request before I assign this

**Comment by sumitshinde-84** [comment]
Thank you so much @mozfreddyb

**Comment by sumitshinde-84** [comment]
@mozfreddyb  If I am mistaken, please kindly bring it to my attention , Thanks @mozfreddyb

**Comment by mozfreddyb** [comment]
Looks like #220 did not fully complete this, @sumitshinde-84.
Can you take the patch from #215 into account, increase the version number for the compat plugin and make it work with that?

Error log at https://github.com/mozilla/sanitizer-polyfill/actions/runs/4729298430/jobs/8391757223?pr=215

**Comment by sumitshinde-84** [comment]
To fix this issue, we can update  code to handle the case where Sanitizer is not supported in Safari 15.6 and iOS Safari 15.6. Here's an example of how we can modify  code to handle this scenario:

/* globals Sanitizer */
const inputEl = document.getElementById("input");
const toutEl = document.getElementById("textoutput");
const houtEl = document.getElementById("htmloutput");

addEventListener("load", function () {
  inputEl.onkeyup = doSanitize;
  // smoke test
  console.log("typeof Sanitizer: " + typeof Sanitizer);
  try {
    // eslint-disable-next-line compat/compat
    window.s = new Sanitizer();
  } catch (e) {
    console.warn("Sanitizer is not a constructor:", e);
    window.s = null; // Set window.s to null if Sanitizer is not supported
  }
});

/**
 *
 */
// eslint-disable-next-line no-unused-vars
function fillExample() {
  inputEl.value = `<p>hi! <svg/onload="alert(1)" />well <em>please</em> <a href="javascript:alert(2)" title="pretty-please">click me!</a>`;
}

/**
 *
 */
function doSanitize() {
  /* globals contextSelect */
  const context = contextSelect.value;
  const inputValue = inputEl.value;
  const contextEl = document.createElement(context);
  if (window.s) { // Check if Sanitizer is supported before using it
    contextEl.setHTML(inputValue, { sanitizer: window.s });
  } else {
    contextEl.innerHTML = inputValue; // Use innerHTML directly if Sanitizer is not supported
  }
  toutEl.value = contextEl.outerHTML;
  houtEl.replaceChildren(contextEl);
}

**Comment by sumitshinde-84** [comment]
yes ,why not !

**Comment by mozfreddyb** [comment]
it worked \o/
thank you!

**Comment by mozfreddyb** [comment]
Unfortunately, my team does not have any internship or full-time opportunities for frontend develoeprs.
If you want to find the open roles at Mozilla, please take a look at https://www.mozilla.org/en-US/careers/listings/ and apply directly through the portal. Your profile says that you're in India and it looks like we do not have any positions outside of USA and Europe at this time.
