### ISSUE TITLE
Set up a system for vendoring DOMPurify

### ISSUE THREAD

**Issue by 0xedward** [mozilla/sanitizer-polyfill#39]

**Comment by mozfreddyb** [comment]
This could require some outside help, but I feel obliged to mention that **this might not be easy.**

Here are the requirements:
Set up some automation that can help get & update the dompurify library into `vendor/`. This should happen semi-automatically with something like dependabot.

Unfortunately, dependabot itself doesnt seem to work (at least from looking at their docs).
