### ISSUE TITLE
implement a _sanitizeDocFragment()

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/sanitizer-polyfill#4]
Implement a function that takes a DocumentFragment and sanitizes the tree based upon a config.
The config should be of the form as specified in https://wicg.github.io/sanitizer-api/#config

There are some pitfalls with walking over a DOM due to [DOM Clobbering](https://portswigger.net/web-security/dom-based/dom-clobbering).

Using a NodeIterator to walk the elements and their attributes might help avoid some of those, but not all. Inspiration and code might be drawn from DOMPurify's ` sanitzeElements()` as well as the top-level `sanitize()` method (for easier searching, that method is declared as  `DOMPurify.sanitize = function` somewhere in the [file](https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L800)). This should be possible because DOMPurify is currently dual-licensed, including MPL-2.0.

**Comment by 0xedward** [comment]
Related comment for reference - https://github.com/0xedward/sanitizer-polyfill/pull/1#discussion_r663741372
