### ISSUE TITLE
Improve button-UI and modify JavaScript in demo/index.html to align with current API (Follow-up of #21)

### ISSUE THREAD

**Issue by mozfreddyb** [mozilla/sanitizer-polyfill#45]
The logic in the demo assumes there are methods on the Sanitizer object that may no longer exist.

Rough proposal for new UI:
1) fill input with an example 
2) a drop-downselector to pick some of predefined context element (`<div>`, `<table>`, `<select>`)
3) button that says `context.setHTML()` and creates the context element (selected above) on the-fly (using document.createElement) to be appended to the preview

**Comment by Bl4ck-h00d** [comment]
I will get to it.

**Comment by Bl4ck-h00d** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/61791315/129777685-0ed1a8be-816b-44f2-b0bf-20ff38715315.gif)

I have done changes to the previous version. Do we want something like this?

**Comment by mozfreddyb** [comment]
It's really hard to judge from just a video... Please share a Pull Request

N.B: The String/Document/DocumentFragment stuff can go.

**Comment by Bl4ck-h00d** [comment]
#46
