### ISSUE TITLE
setting up "config" object

### ISSUE THREAD

**Issue by Bl4ck-h00d** [mozilla/sanitizer-polyfill#56]
I would like to work on the "config" object for specifying allowed elements, attributes, etc.

**Comment by 0xedward** [comment]
Hey @Bl4ck-h00d! :)

Unfortunately, the work you mentioned for the sanitizer object has already been done (See `_normalizeConfig`, `_transformConfig`, `getDefaultConfiguration` in [`src/sanitizer.js`]( https://github.com/mozilla/sanitizer-polyfill/blob/main/src/sanitizer.js))

But there is still some work left to do for validating custom elements in `_normalizeConfig` if you're interested - https://github.com/mozilla/sanitizer-polyfill/issues/33

Going to close this issue, but feel free to reopen or file a new issue if there's something specific to the configuration object from [the spec](https://wicg.github.io/sanitizer-api/) that we haven't implemented yet :)
